"""Draw the MeTube mark: a red heart with a black, round-cornered play triangle in it, on black.

One geometry, three outputs: the launcher vectors (ic_launcher_foreground / _monochrome), the in-app
mark (ic_metube_mark), and the PNG mipmaps for launchers without adaptive icons plus the README icon.
The heart is Material's "favorite" outline (24-unit grid, Apache 2.0); everything is placed on that
grid and scaled into the 108-unit adaptive-icon grid. Usage: python tools/render_icon.py
"""
import pathlib

from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "smarttubetv" / "src" / "stmobile" / "res"
GROUND = (0x00, 0x00, 0x00)
RED = (0xFF, 0x45, 0x3A)
SS = 4  # supersampling

# Material "favorite", absolute segments on the 24 grid.
HEART_START = (12, 21.35)
HEART = [
    ("L", (10.55, 20.03)),
    ("C", (5.4, 15.36), (2, 12.28), (2, 8.5)),
    ("C", (2, 5.42), (4.42, 3), (7.5, 3)),
    ("C", (9.24, 3), (10.91, 3.81), (12, 5.09)),
    ("C", (13.09, 3.81), (14.76, 3), (16.5, 3)),
    ("C", (19.58, 3), (22, 5.42), (22, 8.5)),
    ("C", (22, 12.28), (18.6, 15.36), (13.45, 20.04)),
    ("L", HEART_START),
]
# The play triangle (24 grid), nudged right of the heart's centre line so it reads as centred.
TRIANGLE = [(9.6, 7.45), (9.6, 14.5), (15.9, 10.97)]
CORNER = 0.95  # triangle corner rounding, 24 grid

# 24 grid -> 108 grid: the launcher heart spans x 27..81 inside the 66-unit safe zone; the in-app
# mark fills its whole box.
LAUNCHER = (2.7, 21.6, 22.9)
MARK = (5.0, -6.0, -6.9)


def rounded_triangle():
    """The triangle as a closed path whose corners are quadratic curves of radius CORNER."""
    pts = TRIANGLE
    segs = []
    for i, corner in enumerate(pts):
        prev, nxt = pts[i - 1], pts[(i + 1) % 3]
        a = toward(corner, prev, CORNER)
        b = toward(corner, nxt, CORNER)
        segs.append((a, corner, b))
    return segs


def toward(p, q, d):
    dx, dy = q[0] - p[0], q[1] - p[1]
    n = (dx * dx + dy * dy) ** 0.5
    return (p[0] + dx / n * d, p[1] + dy / n * d)


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def heart_path_data():
    out = [f"M{f(HEART_START[0])},{f(HEART_START[1])}"]
    for seg in HEART:
        if seg[0] == "L":
            out.append(f"L{f(seg[1][0])},{f(seg[1][1])}")
        else:
            out.append("C" + " ".join(f"{f(x)},{f(y)}" for x, y in seg[1:]))
    return "".join(out) + "Z"


def triangle_path_data():
    segs = rounded_triangle()
    out = [f"M{f(segs[0][2][0])},{f(segs[0][2][1])}"]
    for a, corner, b in segs[1:] + segs[:1]:
        out.append(f"L{f(a[0])},{f(a[1])}Q{f(corner[0])},{f(corner[1])} {f(b[0])},{f(b[1])}")
    return "".join(out) + "Z"


def vector(comment, size_dp, transform, heart_color, triangle_color, cutout):
    scale, tx, ty = transform
    if cutout:  # themed icon: one shape, the triangle punched out of the heart
        body = (f'        <path\n            android:fillColor="{heart_color}"\n'
                f'            android:fillType="evenOdd"\n'
                f'            android:pathData="{heart_path_data()}{triangle_path_data()}" />\n')
    else:
        body = (f'        <path\n            android:fillColor="{heart_color}"\n'
                f'            android:pathData="{heart_path_data()}" />\n'
                f'        <path\n            android:fillColor="{triangle_color}"\n'
                f'            android:pathData="{triangle_path_data()}" />\n')
    return (f'<?xml version="1.0" encoding="utf-8"?>\n<!-- {comment}\n'
            f'     Generated by tools/render_icon.py - edit the geometry there. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp"\n    android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            f'    <group\n        android:scaleX="{scale}"\n        android:scaleY="{scale}"\n'
            f'        android:translateX="{tx}"\n        android:translateY="{ty}">\n'
            f'{body}    </group>\n</vector>\n')


def cubic(p0, p1, p2, p3, n=48):
    pts = []
    for i in range(1, n + 1):
        t = i / n
        u = 1 - t
        pts.append((u ** 3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t ** 3 * p3[0],
                    u ** 3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t ** 3 * p3[1]))
    return pts


def quad(p0, p1, p2, n=16):
    return [((1 - t) ** 2 * p0[0] + 2 * (1 - t) * t * p1[0] + t * t * p2[0],
             (1 - t) ** 2 * p0[1] + 2 * (1 - t) * t * p1[1] + t * t * p2[1])
            for t in (i / n for i in range(n + 1))]


def heart_points():
    pts = [HEART_START]
    for seg in HEART:
        if seg[0] == "L":
            pts.append(seg[1])
        else:
            pts += cubic(pts[-1], *seg[1:])
    return pts


def triangle_points():
    pts = []
    for a, corner, b in rounded_triangle():
        pts += quad(a, corner, b)
    return pts


def render(size, crop=18):
    """The adaptive icon as a legacy launcher shows it: the centre 72 units, squircle-masked."""
    full = size * 108 // (108 - 2 * crop) * SS
    u = full / 108
    scale, tx, ty = LAUNCHER

    def place(points):
        return [((x * scale + tx) * u, (y * scale + ty) * u) for x, y in points]

    img = Image.new("RGBA", (full, full), GROUND + (255,))
    d = ImageDraw.Draw(img)
    d.polygon(place(heart_points()), fill=RED)
    d.polygon(place(triangle_points()), fill=GROUND)
    c = round(crop * u)
    img = img.crop((c, c, full - c, full - c))
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, img.size[0] - 1, img.size[1] - 1],
                                           radius=img.size[0] * 0.23, fill=255)
    img.putalpha(mask)
    return img.resize((size, size), Image.LANCZOS)


if __name__ == "__main__":
    drawable = RES / "drawable"
    (drawable / "ic_launcher_foreground.xml").write_text(vector(
        "METUBE: the mark - a red heart with a black play triangle, inside the 66dp safe zone.",
        108, LAUNCHER, "#FF453A", "#000000", False), encoding="utf-8")
    (drawable / "ic_launcher_monochrome.xml").write_text(vector(
        "METUBE: themed-icon (Android 13+) mark - the heart with the play triangle cut out.",
        108, LAUNCHER, "#FFFFFF", None, True), encoding="utf-8")
    (drawable / "ic_metube_mark.xml").write_text(vector(
        "METUBE: the in-app mark (brand pill) - the launcher heart and play triangle.",
        22, MARK, "#FF453A", "#000000", False), encoding="utf-8")
    for density, size in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        icon = render(size)
        for name in ("app_icon.png", "app_icon_alt.png"):
            icon.save(RES / f"mipmap-{density}" / name)
    render(512).save(ROOT / ".github" / "assets" / "icon.png")
    print("ok")
